services:
  - type: web
    name: dumbo-finance-app
    runtime: node
    plan: free
    buildCommand: sed -i 's/provider = "sqlite"/provider = "postgresql"/' prisma/schema.prisma && npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dumbo-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: NEXTAUTH_SECRET
        generateValue: true

databases:
  - name: dumbo-db
    plan: free
